In [2]:
from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold


import numpy
import pandas as pd
import tensorflow as tf

In [3]:
# seed 값 설정
seed = 0
numpy.random.seed(seed)
tf.set_random_seed(seed)


In [10]:
df = pd.read_csv('example/deeplearning/dataset/sonar.csv', header=None)

dataset = df.values
X = dataset[:,0:60]
Y_obj = dataset[:,60]

print(dataset.shape, X.shape, Y_obj.shape)
print(X)
print(Y_obj)

(208, 61) (208, 60) (208,)
[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' '

In [11]:
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)


In [14]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [19]:
# 10개의 파일로 쪼갬
n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)


StratifiedKFold(n_splits=10, random_state=0, shuffle=True)

In [40]:
for x, y in skf.split(X, Y):
    print(x.shape, y.shape)
    print(x, y) 

(186,) (22,)
[  0   1   2   3   4   5   6   7   8   9  10  11  13  14  15  16  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  61  62  63  64  65  66  67  68  69  71  72  73  75  76  77
  79  80  82  83  84  86  87  88  89  90  91  93  94  95  96  97  98 100
 101 102 103 105 106 108 109 110 111 112 114 115 116 117 118 120 122 123
 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141
 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 174 175 176 177 178 179
 180 181 182 183 184 185 188 189 190 191 192 193 194 195 197 198 200 201
 202 203 204 205 206 207] [ 12  17  18  60  70  74  78  81  85  92  99 104 107 113 119 121 142 173
 186 187 196 199]
(187,) (21,)
[  0   2   3   4   8  10  11  12  13  14  16  17  18  19  20  21  22  23
  24  25  26  27  28  30  31  32  33  34  35  36  37  

In [38]:

# 빈 accuracy 배열
accuracy = []

# 모델의 설정, 컴파일, 실행
for train, test in skf.split(X, Y):
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='mean_squared_error',
                  optimizer='adam',
                  metrics=['accuracy'])
    model.fit(X[train], Y[train], epochs=100, batch_size=5)
    k_accuracy = "%.4f" % (model.evaluate(X[test], Y[test])[1])
    accuracy.append(k_accuracy)              




W0911 01:55:03.451116 22508 deprecation_wrapper.py:119] From C:\Users\y2k43\Anaconda3\envs\venv\lib\site-packages\keras-2.2.4-py3.6.egg\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0911 01:55:03.454107 22508 deprecation_wrapper.py:119] From C:\Users\y2k43\Anaconda3\envs\venv\lib\site-packages\keras-2.2.4-py3.6.egg\keras\backend\tensorflow_backend.py:529: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0911 01:55:03.458099 22508 deprecation_wrapper.py:119] From C:\Users\y2k43\Anaconda3\envs\venv\lib\site-packages\keras-2.2.4-py3.6.egg\keras\backend\tensorflow_backend.py:4420: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0911 01:55:03.520962 22508 deprecation_wrapper.py:119] From C:\Users\y2k43\Anaconda3\envs\venv\lib\site-packages\keras-2.2.4-py3.6.egg\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Pl

Epoch 1/100
186/186 [==============================] - 1s 4ms/step - loss: 0.2534 - acc: 0.4839
Epoch 2/100
186/186 [==============================] - 0s 1ms/step - loss: 0.2456 - acc: 0.5430
Epoch 3/100
186/186 [==============================] - 0s 593us/step - loss: 0.2422 - acc: 0.5376
Epoch 4/100
186/186 [==============================] - 0s 407us/step - loss: 0.2380 - acc: 0.5699
Epoch 5/100
186/186 [==============================] - 0s 414us/step - loss: 0.2316 - acc: 0.5591
Epoch 6/100
186/186 [==============================] - 0s 386us/step - loss: 0.2205 - acc: 0.6613
Epoch 7/100
186/186 [==============================] - 0s 419us/step - loss: 0.2108 - acc: 0.6398
Epoch 8/100
186/186 [==============================] - 0s 408us/step - loss: 0.1995 - acc: 0.6935
Epoch 9/100
186/186 [==============================] - 0s 424us/step - loss: 0.1898 - acc: 0.6935
Epoch 10/100
186/186 [==============================] - 0s 424us/step - loss: 0.1802 - acc: 0.7688
Epoch 11/100
186/186 [=

186/186 [==============================] - 0s 463us/step - loss: 0.0557 - acc: 0.9462
Epoch 84/100
186/186 [==============================] - 0s 424us/step - loss: 0.0590 - acc: 0.9247
Epoch 85/100
186/186 [==============================] - 0s 495us/step - loss: 0.0660 - acc: 0.9194
Epoch 86/100
186/186 [==============================] - 0s 454us/step - loss: 0.0684 - acc: 0.9140
Epoch 87/100
186/186 [==============================] - 0s 465us/step - loss: 0.0573 - acc: 0.9516
Epoch 88/100
186/186 [==============================] - 0s 451us/step - loss: 0.0624 - acc: 0.9194
Epoch 89/100
186/186 [==============================] - 0s 440us/step - loss: 0.0557 - acc: 0.9301
Epoch 90/100
186/186 [==============================] - 0s 461us/step - loss: 0.0522 - acc: 0.9516
Epoch 91/100
186/186 [==============================] - 0s 543us/step - loss: 0.0515 - acc: 0.9355
Epoch 92/100
186/186 [==============================] - 0s 566us/step - loss: 0.0525 - acc: 0.9301
Epoch 93/100
186/186 [=

187/187 [==============================] - 0s 413us/step - loss: 0.0712 - acc: 0.9251
Epoch 66/100
187/187 [==============================] - 0s 432us/step - loss: 0.0700 - acc: 0.9144
Epoch 67/100
187/187 [==============================] - 0s 437us/step - loss: 0.0701 - acc: 0.9037
Epoch 68/100
187/187 [==============================] - 0s 409us/step - loss: 0.0675 - acc: 0.9144
Epoch 69/100
187/187 [==============================] - 0s 472us/step - loss: 0.0672 - acc: 0.9144
Epoch 70/100
187/187 [==============================] - 0s 352us/step - loss: 0.0664 - acc: 0.9358
Epoch 71/100
187/187 [==============================] - 0s 343us/step - loss: 0.0662 - acc: 0.9198
Epoch 72/100
187/187 [==============================] - 0s 437us/step - loss: 0.0672 - acc: 0.9358
Epoch 73/100
187/187 [==============================] - 0s 379us/step - loss: 0.0632 - acc: 0.9305
Epoch 74/100
187/187 [==============================] - 0s 412us/step - loss: 0.0611 - acc: 0.9305
Epoch 75/100
187/187 [=

187/187 [==============================] - 0s 558us/step - loss: 0.0906 - acc: 0.8930
Epoch 48/100
187/187 [==============================] - 0s 529us/step - loss: 0.0896 - acc: 0.8824
Epoch 49/100
187/187 [==============================] - 0s 299us/step - loss: 0.0815 - acc: 0.9037
Epoch 50/100
187/187 [==============================] - 0s 264us/step - loss: 0.0812 - acc: 0.8930
Epoch 51/100
187/187 [==============================] - 0s 453us/step - loss: 0.0841 - acc: 0.8877
Epoch 52/100
187/187 [==============================] - 0s 481us/step - loss: 0.0803 - acc: 0.9198
Epoch 53/100
187/187 [==============================] - 0s 499us/step - loss: 0.0759 - acc: 0.9198
Epoch 54/100
187/187 [==============================] - 0s 434us/step - loss: 0.0751 - acc: 0.9091
Epoch 55/100
187/187 [==============================] - 0s 444us/step - loss: 0.0739 - acc: 0.9251
Epoch 56/100
187/187 [==============================] - 0s 486us/step - loss: 0.0789 - acc: 0.8984
Epoch 57/100
187/187 [=

187/187 [==============================] - 0s 437us/step - loss: 0.1032 - acc: 0.8663
Epoch 30/100
187/187 [==============================] - 0s 442us/step - loss: 0.1058 - acc: 0.8503
Epoch 31/100
187/187 [==============================] - 0s 425us/step - loss: 0.0996 - acc: 0.8930
Epoch 32/100
187/187 [==============================] - 0s 541us/step - loss: 0.0984 - acc: 0.8770
Epoch 33/100
187/187 [==============================] - 0s 565us/step - loss: 0.0982 - acc: 0.8717
Epoch 34/100
187/187 [==============================] - 0s 609us/step - loss: 0.0976 - acc: 0.8877
Epoch 35/100
187/187 [==============================] - 0s 524us/step - loss: 0.0938 - acc: 0.8824
Epoch 36/100
187/187 [==============================] - 0s 532us/step - loss: 0.0912 - acc: 0.8984
Epoch 37/100
187/187 [==============================] - 0s 522us/step - loss: 0.0930 - acc: 0.8877
Epoch 38/100
187/187 [==============================] - 0s 535us/step - loss: 0.0888 - acc: 0.8930
Epoch 39/100
187/187 [=

187/187 [==============================] - 0s 476us/step - loss: 0.1463 - acc: 0.8021
Epoch 12/100
187/187 [==============================] - 0s 427us/step - loss: 0.1363 - acc: 0.8610
Epoch 13/100
187/187 [==============================] - 0s 503us/step - loss: 0.1388 - acc: 0.8021
Epoch 14/100
187/187 [==============================] - 0s 919us/step - loss: 0.1268 - acc: 0.8556 0s - loss: 0.1475 - acc: 0.8
Epoch 15/100
187/187 [==============================] - 0s 749us/step - loss: 0.1244 - acc: 0.8235
Epoch 16/100
187/187 [==============================] - 0s 775us/step - loss: 0.1196 - acc: 0.8556
Epoch 17/100
187/187 [==============================] - 0s 908us/step - loss: 0.1185 - acc: 0.8503
Epoch 18/100
187/187 [==============================] - 0s 511us/step - loss: 0.1124 - acc: 0.8503
Epoch 19/100
187/187 [==============================] - 0s 487us/step - loss: 0.1096 - acc: 0.8717
Epoch 20/100
187/187 [==============================] - 0s 474us/step - loss: 0.1069 - acc: 0

187/187 [==============================] - 0s 438us/step - loss: 0.0088 - acc: 0.9947
Epoch 94/100
187/187 [==============================] - 0s 439us/step - loss: 0.0077 - acc: 0.9947
Epoch 95/100
187/187 [==============================] - 0s 430us/step - loss: 0.0071 - acc: 0.9947
Epoch 96/100
187/187 [==============================] - 0s 441us/step - loss: 0.0060 - acc: 1.0000
Epoch 97/100
187/187 [==============================] - 0s 1ms/step - loss: 0.0058 - acc: 1.0000
Epoch 98/100
187/187 [==============================] - 0s 610us/step - loss: 0.0058 - acc: 0.9947
Epoch 99/100
187/187 [==============================] - 0s 316us/step - loss: 0.0053 - acc: 1.0000
Epoch 100/100
21/21 [==============================] - 0s 9ms/step
Epoch 1/100
187/187 [==============================] - 1s 4ms/step - loss: 0.2604 - acc: 0.4652
Epoch 2/100
187/187 [==============================] - 0s 428us/step - loss: 0.2475 - acc: 0.5241
Epoch 3/100
187/187 [==============================] - 0s 444

187/187 [==============================] - 0s 756us/step - loss: 0.0340 - acc: 0.9679
Epoch 76/100
187/187 [==============================] - 0s 591us/step - loss: 0.0306 - acc: 0.9786
Epoch 77/100
187/187 [==============================] - 0s 539us/step - loss: 0.0352 - acc: 0.9679
Epoch 78/100
187/187 [==============================] - 0s 623us/step - loss: 0.0333 - acc: 0.9786
Epoch 79/100
187/187 [==============================] - 0s 739us/step - loss: 0.0330 - acc: 0.9733
Epoch 80/100
187/187 [==============================] - 0s 753us/step - loss: 0.0362 - acc: 0.9572
Epoch 81/100
187/187 [==============================] - 0s 472us/step - loss: 0.0292 - acc: 0.9733
Epoch 82/100
187/187 [==============================] - 0s 424us/step - loss: 0.0287 - acc: 0.9679
Epoch 83/100
187/187 [==============================] - 0s 491us/step - loss: 0.0269 - acc: 0.9786
Epoch 84/100
187/187 [==============================] - 0s 456us/step - loss: 0.0284 - acc: 0.9786
Epoch 85/100
187/187 [=

187/187 [==============================] - 0s 525us/step - loss: 0.0641 - acc: 0.9251
Epoch 58/100
187/187 [==============================] - 0s 453us/step - loss: 0.0638 - acc: 0.9412
Epoch 59/100
187/187 [==============================] - 0s 459us/step - loss: 0.0614 - acc: 0.9412
Epoch 60/100
187/187 [==============================] - 0s 540us/step - loss: 0.0610 - acc: 0.9412
Epoch 61/100
187/187 [==============================] - 0s 517us/step - loss: 0.0621 - acc: 0.9144
Epoch 62/100
187/187 [==============================] - 0s 525us/step - loss: 0.0618 - acc: 0.9358
Epoch 63/100
187/187 [==============================] - 0s 432us/step - loss: 0.0565 - acc: 0.9465
Epoch 64/100
187/187 [==============================] - 0s 399us/step - loss: 0.0561 - acc: 0.9465
Epoch 65/100
187/187 [==============================] - 0s 450us/step - loss: 0.0541 - acc: 0.9305
Epoch 66/100
187/187 [==============================] - 0s 477us/step - loss: 0.0532 - acc: 0.9519
Epoch 67/100
187/187 [=

188/188 [==============================] - 0s 470us/step - loss: 0.0838 - acc: 0.8936
Epoch 40/100
188/188 [==============================] - 0s 439us/step - loss: 0.0854 - acc: 0.8883
Epoch 41/100
188/188 [==============================] - 0s 529us/step - loss: 0.0799 - acc: 0.9096
Epoch 42/100
188/188 [==============================] - 0s 516us/step - loss: 0.0783 - acc: 0.9043
Epoch 43/100
188/188 [==============================] - 0s 489us/step - loss: 0.0733 - acc: 0.9255
Epoch 44/100
188/188 [==============================] - 0s 470us/step - loss: 0.0704 - acc: 0.9309
Epoch 45/100
188/188 [==============================] - 0s 563us/step - loss: 0.0698 - acc: 0.9255
Epoch 46/100
188/188 [==============================] - 0s 678us/step - loss: 0.0687 - acc: 0.9309
Epoch 47/100
188/188 [==============================] - 0s 793us/step - loss: 0.0717 - acc: 0.9255
Epoch 48/100
188/188 [==============================] - 0s 350us/step - loss: 0.0707 - acc: 0.9362
Epoch 49/100
188/188 [=

188/188 [==============================] - 0s 709us/step - loss: 0.1259 - acc: 0.8511
Epoch 22/100
188/188 [==============================] - 0s 557us/step - loss: 0.1246 - acc: 0.8617
Epoch 23/100
188/188 [==============================] - 0s 556us/step - loss: 0.1241 - acc: 0.8351
Epoch 24/100
188/188 [==============================] - 0s 556us/step - loss: 0.1239 - acc: 0.8404
Epoch 25/100
188/188 [==============================] - 0s 647us/step - loss: 0.1161 - acc: 0.8617
Epoch 26/100
188/188 [==============================] - 0s 579us/step - loss: 0.1153 - acc: 0.8564
Epoch 27/100
188/188 [==============================] - 0s 531us/step - loss: 0.1155 - acc: 0.8457
Epoch 28/100
188/188 [==============================] - 0s 625us/step - loss: 0.1132 - acc: 0.8723
Epoch 29/100
188/188 [==============================] - 0s 634us/step - loss: 0.1090 - acc: 0.8670
Epoch 30/100
188/188 [==============================] - 0s 641us/step - loss: 0.1101 - acc: 0.8511
Epoch 31/100
188/188 [=

188/188 [==============================] - 0s 445us/step - loss: 0.2406 - acc: 0.5851
Epoch 4/100
188/188 [==============================] - 0s 426us/step - loss: 0.2355 - acc: 0.6117
Epoch 5/100
188/188 [==============================] - 0s 554us/step - loss: 0.2275 - acc: 0.6596
Epoch 6/100
188/188 [==============================] - 0s 1ms/step - loss: 0.2226 - acc: 0.6755
Epoch 7/100
188/188 [==============================] - 0s 907us/step - loss: 0.2200 - acc: 0.6755
Epoch 8/100
188/188 [==============================] - 0s 895us/step - loss: 0.2019 - acc: 0.7128
Epoch 9/100
188/188 [==============================] - 0s 820us/step - loss: 0.2047 - acc: 0.6862
Epoch 10/100
188/188 [==============================] - 0s 849us/step - loss: 0.1845 - acc: 0.8085
Epoch 11/100
188/188 [==============================] - 0s 814us/step - loss: 0.1704 - acc: 0.8191
Epoch 12/100
188/188 [==============================] - 0s 1ms/step - loss: 0.1604 - acc: 0.8138
Epoch 13/100
188/188 [===========

KeyboardInterrupt: 

In [41]:
# 결과 출력
print("\n %.f fold accuracy:" % n_fold, accuracy)


 10 fold accuracy: ['0.8636', '0.8571', '0.7619', '0.9524', '0.8571', '0.8571', '0.9048', '0.9500', '0.8000']
